language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
before_install:
- "sudo apt-get -qq update"
- "sudo apt-get install -y -qq python3 python3-pip build-essential"
- "sudo apt-get build-dep python3-lxml"
install:
- "pip install ."
script:
- "nosetests"
