language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6-dev'
- 'nightly'
before_install:
- "sudo apt-get -qq update"
- "sudo apt-get install -y -qq libxml2-dev libxslt-dev python-dev"
install:
- "pip install ."
script:
- "nosetests"
